### ISSUE TITLE
Python3 problem with xmlstore

### ISSUE THREAD

**Issue by xlange** [BoldingBruggeman/xmlstore#1]
I recently had some problems creating namelists for getm with python3 in function toNamelistString in xmlstore/datatypes.py.

Changing
result.append((','.join(map(str,inds)+[':']),','.join(strings)))
into 
result.append((','.join(list(map(str,inds))+[':']),','.join(strings)))

solved the problem for me.

**Comment by jornbr** [comment]
Thanks for reporting this. It has now been fixed in xmlstore 0.9.6
